### ISSUE TITLE
WIC Mobile Website

### ISSUE THREAD

**Issue by nealf** [CodeforNRV/Projects#28]
The WIC (Women, Infants, Children) social services program requires participants to review educational material on a frequent basis. That current process involves accessing a Flash website and then printing a certificate. Given the number of people who rely solely on mobile web access, providing a website that is mobile friendly and a way to digitally sign and submit the certificate would be incredibly helpful to participants.

https://github.com/CodeforNRV/WIC-Education-Website

**Comment by nealf** [comment]
David Moore presented this idea in December 2015. He is currently doing some research and reaching out to people and groups to determine the feasibility from a non-technical standpoint.

**Comment by dmoorevtedu** [comment]
As a WIC parent
I want an app that remembers my WIC information (ID number) and keeps track of when I need to complete training or office visits and send me a notification
so that I can keep my eligibility from lapsing and I can continue to receive my WIC benefits.

**Comment by dmoorevtedu** [comment]
As a WIC parent
I want to be able to identify and update my local heath department location
so that the app can know where to send my compliance information when I complete something.

**Comment by dmoorevtedu** [comment]
As a local health district WIC coordinator
I want to be able to select and maintain my information delivery preference (email address - possibly fax)
so that I will receive the documentation I need to update compliance records for a client of our office when they do their training online.

**Comment by dmoorevtedu** [comment]
As a WIC parent
I want to complete an online training using a low end smartphone
so that I can meet the training requirement with equipment I actually own and I don't have to buy a computer or go use a public library computer

**Comment by dmoorevtedu** [comment]
As a WIC parent 
I want to digitally sign any other WIC paperwork required for quarterly check ins
so that I can comply without driving to the WIC office.

**Comment by dmoorevtedu** [comment]
As a WIC parent
when I complete training, I want my training certificate to be digitally sent to the right health department contact for my current health district office
so that I don;t have to figure out a way to print it and mail/drive it to the WIC office

**Comment by ghthor** [comment]
[Current Flash Version](http://healthbitesva.org/)
Most of the data is stored in xml that is fetched from the server.

**Comment by nealf** [comment]
That website is no more, hopefully replaced with a better version.

**Comment by ghthor** [comment]
@nealf Thanks for all the encouraging hard work you did on this back then. I doubt I'd be where I am if I hadn't paired up with you guys for that hackathon!

**Comment by nealf** [comment]
@ghthor Thanks for all of the hard work you put in with Code for NRV! It was great getting to know you, and I hope you are doing well these days!
